- name: play to create a virtual machine
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Run command if /path/to/database does not exist (with 'cmd' parameter)
      command: lsblk
        
        
